/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceType = IDL.Variant({
  'bridalPackage' : IDL.Null,
  'haircut' : IDL.Null,
  'eyebrowThreading' : IDL.Null,
  'nailCare' : IDL.Null,
  'makeup' : IDL.Null,
  'hairColoring' : IDL.Null,
  'waxing' : IDL.Null,
  'facial' : IDL.Null,
});
export const Appointment = IDL.Record({
  'service' : ServiceType,
  'customerName' : IDL.Text,
  'email' : IDL.Text,
  'preferredTimeSlot' : IDL.Text,
  'preferredDate' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'submitAppointment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ServiceType,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceType = IDL.Variant({
    'bridalPackage' : IDL.Null,
    'haircut' : IDL.Null,
    'eyebrowThreading' : IDL.Null,
    'nailCare' : IDL.Null,
    'makeup' : IDL.Null,
    'hairColoring' : IDL.Null,
    'waxing' : IDL.Null,
    'facial' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'service' : ServiceType,
    'customerName' : IDL.Text,
    'email' : IDL.Text,
    'preferredTimeSlot' : IDL.Text,
    'preferredDate' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'submitAppointment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ServiceType,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };