/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'service' : ServiceType,
  'customerName' : string,
  'email' : string,
  'preferredTimeSlot' : string,
  'preferredDate' : string,
  'notes' : [] | [string],
  'phoneNumber' : string,
}
export interface Inquiry {
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type ServiceType = { 'bridalPackage' : null } |
  { 'haircut' : null } |
  { 'eyebrowThreading' : null } |
  { 'nailCare' : null } |
  { 'makeup' : null } |
  { 'hairColoring' : null } |
  { 'waxing' : null } |
  { 'facial' : null };
export interface _SERVICE {
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'submitAppointment' : ActorMethod<
    [string, string, string, ServiceType, string, string, [] | [string]],
    undefined
  >,
  'submitInquiry' : ActorMethod<[string, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];