/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Inquiry {
    name: string;
    email: string;
    message: string;
    phone: string;
}
export interface Appointment {
    service: ServiceType;
    customerName: string;
    email: string;
    preferredTimeSlot: string;
    preferredDate: string;
    notes?: string;
    phoneNumber: string;
}
export enum ServiceType {
    bridalPackage = "bridalPackage",
    haircut = "haircut",
    eyebrowThreading = "eyebrowThreading",
    nailCare = "nailCare",
    makeup = "makeup",
    hairColoring = "hairColoring",
    waxing = "waxing",
    facial = "facial"
}
export interface backendInterface {
    getAllAppointments(): Promise<Array<Appointment>>;
    getAllInquiries(): Promise<Array<Inquiry>>;
    submitAppointment(customerName: string, phoneNumber: string, email: string, service: ServiceType, preferredDate: string, preferredTimeSlot: string, notes: string | null): Promise<void>;
    submitInquiry(name: string, email: string, phone: string, message: string): Promise<void>;
}
import type { Appointment as _Appointment, ServiceType as _ServiceType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppointments();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppointments();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return result;
        }
    }
    async submitAppointment(arg0: string, arg1: string, arg2: string, arg3: ServiceType, arg4: string, arg5: string, arg6: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAppointment(arg0, arg1, arg2, to_candid_ServiceType_n7(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAppointment(arg0, arg1, arg2, to_candid_ServiceType_n7(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async submitInquiry(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_Appointment_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    service: _ServiceType;
    customerName: string;
    email: string;
    preferredTimeSlot: string;
    preferredDate: string;
    notes: [] | [string];
    phoneNumber: string;
}): {
    service: ServiceType;
    customerName: string;
    email: string;
    preferredTimeSlot: string;
    preferredDate: string;
    notes?: string;
    phoneNumber: string;
} {
    return {
        service: from_candid_ServiceType_n4(_uploadFile, _downloadFile, value.service),
        customerName: value.customerName,
        email: value.email,
        preferredTimeSlot: value.preferredTimeSlot,
        preferredDate: value.preferredDate,
        notes: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.notes)),
        phoneNumber: value.phoneNumber
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bridalPackage: null;
} | {
    haircut: null;
} | {
    eyebrowThreading: null;
} | {
    nailCare: null;
} | {
    makeup: null;
} | {
    hairColoring: null;
} | {
    waxing: null;
} | {
    facial: null;
}): ServiceType {
    return "bridalPackage" in value ? ServiceType.bridalPackage : "haircut" in value ? ServiceType.haircut : "eyebrowThreading" in value ? ServiceType.eyebrowThreading : "nailCare" in value ? ServiceType.nailCare : "makeup" in value ? ServiceType.makeup : "hairColoring" in value ? ServiceType.hairColoring : "waxing" in value ? ServiceType.waxing : "facial" in value ? ServiceType.facial : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n2(_uploadFile, _downloadFile, x));
}
function to_candid_ServiceType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    bridalPackage: null;
} | {
    haircut: null;
} | {
    eyebrowThreading: null;
} | {
    nailCare: null;
} | {
    makeup: null;
} | {
    hairColoring: null;
} | {
    waxing: null;
} | {
    facial: null;
} {
    return value == ServiceType.bridalPackage ? {
        bridalPackage: null
    } : value == ServiceType.haircut ? {
        haircut: null
    } : value == ServiceType.eyebrowThreading ? {
        eyebrowThreading: null
    } : value == ServiceType.nailCare ? {
        nailCare: null
    } : value == ServiceType.makeup ? {
        makeup: null
    } : value == ServiceType.hairColoring ? {
        hairColoring: null
    } : value == ServiceType.waxing ? {
        waxing: null
    } : value == ServiceType.facial ? {
        facial: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
